// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetChartDataHandlerFunc turns a function with the right signature into a get chart data handler
type GetChartDataHandlerFunc func(GetChartDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChartDataHandlerFunc) Handle(params GetChartDataParams) middleware.Responder {
	return fn(params)
}

// GetChartDataHandler interface for that can handle valid get chart data params
type GetChartDataHandler interface {
	Handle(GetChartDataParams) middleware.Responder
}

// NewGetChartData creates a new http.Handler for the get chart data operation
func NewGetChartData(ctx *middleware.Context, handler GetChartDataHandler) *GetChartData {
	return &GetChartData{Context: ctx, Handler: handler}
}

/* GetChartData swagger:route GET /chart/{days} data getChartData

Get chart defi data

*/
type GetChartData struct {
	Context *middleware.Context
	Handler GetChartDataHandler
}

func (o *GetChartData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChartDataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
