// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/polystation/polydefi-api/pkg/openapi/swagger/models"
)

// GetAllDataOKCode is the HTTP code returned for type GetAllDataOK
const GetAllDataOKCode int = 200

/*GetAllDataOK successful operation

swagger:response getAllDataOK
*/
type GetAllDataOK struct {

	/*
	  In: Body
	*/
	Payload models.AllData `json:"body,omitempty"`
}

// NewGetAllDataOK creates GetAllDataOK with default headers values
func NewGetAllDataOK() *GetAllDataOK {

	return &GetAllDataOK{}
}

// WithPayload adds the payload to the get all data o k response
func (o *GetAllDataOK) WithPayload(payload models.AllData) *GetAllDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all data o k response
func (o *GetAllDataOK) SetPayload(payload models.AllData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllData{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllDataNotFoundCode is the HTTP code returned for type GetAllDataNotFound
const GetAllDataNotFoundCode int = 404

/*GetAllDataNotFound not found

swagger:response getAllDataNotFound
*/
type GetAllDataNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetAllDataNotFound creates GetAllDataNotFound with default headers values
func NewGetAllDataNotFound() *GetAllDataNotFound {

	return &GetAllDataNotFound{}
}

// WithPayload adds the payload to the get all data not found response
func (o *GetAllDataNotFound) WithPayload(payload *models.APIResponse) *GetAllDataNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all data not found response
func (o *GetAllDataNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllDataNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
