// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetChartDataParams creates a new GetChartDataParams object
//
// There are no default values defined in the spec.
func NewGetChartDataParams() GetChartDataParams {

	return GetChartDataParams{}
}

// GetChartDataParams contains all the bound params for the get chart data operation
// typically these are obtained from a http.Request
//
// swagger:parameters getChartData
type GetChartDataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Number of days
	  Required: true
	  In: path
	*/
	Days int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetChartDataParams() beforehand.
func (o *GetChartDataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDays, rhkDays, _ := route.Params.GetOK("days")
	if err := o.bindDays(rDays, rhkDays, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDays binds and validates parameter Days from path.
func (o *GetChartDataParams) bindDays(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("days", "path", "int64", raw)
	}
	o.Days = value

	return nil
}
