// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DefiData defi data
//
// swagger:model DefiData
type DefiData struct {

	// Category
	Category string `json:"category"`

	// Name
	Chain string `json:"chain"`

	// Contract Num
	ContractNum int64 `json:"contractNum"`

	// Holders
	Holders int64 `json:"holders"`

	// Holders Change 24h
	HoldersChange24hNum int64 `json:"holdersChange24hNum"`

	// Last Updated
	LastUpdated int64 `json:"lastUpdated"`

	// Locked Usd
	LockedUsd int64 `json:"lockedUsd"`

	// Market Cap
	MarketCap float64 `json:"marketCap"`

	// Market Cap Change 24h
	MarketCapChange24h float64 `json:"marketCapChange24h"`

	// Name
	Name string `json:"name"`

	// Price
	Price float64 `json:"price"`

	// Price Percent Change 24h
	PriceChange24h float64 `json:"priceChange24h"`

	// Token
	Token string `json:"token,omitempty"`

	// TVL Percent Change 24h
	TvlPercentChange24h float64 `json:"tvlPercentChange24h"`

	// Verified
	Verified int64 `json:"verified"`

	// Volume
	Volume int64 `json:"volume"`
}

// Validate validates this defi data
func (m *DefiData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this defi data based on context it is used
func (m *DefiData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefiData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefiData) UnmarshalBinary(b []byte) error {
	var res DefiData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
