// Code generated by go-swagger; DO NOT EDIT.

// Package restapi polydefi
//
//  polydefi v1 api
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//    https
//  Host: polydefi.bitcloud.live
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <apiteam@swagger.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
